### ISSUE TITLE
"Connection is not active, please refresh the page". Websocket connection doesn't work.

### ISSUE THREAD

**Issue by osipenkom** [requestinspector/public-issues#1]
Hello everyone! 

Since yesterday I can see that requestinspector web page can't establish websocket connection and shows "Connection is not active, please refresh the page" error on the main page. 

What is the reason of that and how can I fix that behavior? 

![image](https://github.com/requestinspector/public-issues/assets/13850369/9706a6d2-9f63-46c0-ba44-e3c647d7182a)

**Comment by logocomune** [comment]
To better understand the problem, I need some additional information.

- How long had you been connected before receiving that message?
- Does it happen after xx minutes or randomly?

The error you encountered stems from a loss of connection to the websocket service. The client attempts to reconnect 10 times, after which a page refresh is required.

**Comment by osipenkom** [comment]
Hello @logocomune.

> * How long had you been connected before receiving that message?

It was working fine last time at Friday June 14th. When I opened web page at Monday June 17th it was showing that websocket error.

> * Does it happen after xx minutes or randomly?

I don't know actually when it started. I just opened web page at Monday June 17th and it wasn't working.

> The error you encountered stems from a loss of connection to the websocket service. The client attempts to reconnect 10 times, after which a page refresh is required.

I understand that. That's why I created bug report, to notify you that something is wrong with websocket connection on the web page.

**Comment by logocomune** [comment]
During the weekend, a major update was carried out. No issues with the websocket were found in either the previous or subsequent tests. However, any report cannot be ignored.

By checking the system logs, I do not see any requests to the websocket service for your endpoint.

Could you please verify the following:

- You can open: https://ws.requestinspector.com/health
- Do you have any errors in the browser console (developer tools -> console)?

**Comment by osipenkom** [comment]
Thank you for jumping into it so quickly!

> * You can open: https://ws.requestinspector.com/health

It shows:
>2024-06-18 14:26:03.363520908 +0000 UTC m=+964177.719933962 - OK


> * Do you have any errors in the browser console (developer tools -> console)?

Yes, I do. Please see on the screenshot below
![image](https://github.com/requestinspector/public-issues/assets/13850369/5b936f7b-fc86-4686-8973-dcdb953452de)

**Comment by logocomune** [comment]
@osipenkom
To conduct further tests, I need some data. Could you please contact me via email: info@requestinspector.com?
